# cspell: words msvc, wasip

[graph]
# cargo-deny is really only ever intended to run on the "normal" tier-1 targets
targets = [
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
    "x86_64-pc-windows-msvc",
    "wasm32-unknown-unknown",
    "wasm32-wasip1",
    "wasm32-wasip2",
]

[advisories]
version = 2

[bans]
multiple-versions = "warn"
wildcards = 'deny'

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[licenses]
version = 2
# Don't warn if a listed license isn't found
unused-allowed-license="allow"
# We want really high confidence when inferring licenses from text
confidence-threshold = 0.93
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-DFS-2016",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "BlueOak-1.0.0",
    "Apache-2.0 WITH LLVM-exception",
    "CC0-1.0",
    "ISC",
    "Unicode-3.0",
    "MPL-2.0",
    "Zlib",
    "MIT-0",
]
