VERSION 0.8
FROM golang:1.22.4-alpine3.20

IMPORT ../../earthly/go AS go-ci

# cspell: words onsi ldflags extldflags

fmt:
    DO go-ci+FMT --src="go.mod go.sum cmd pkg"

lint:
    DO go-ci+LINT --src="go.mod go.sum cmd pkg"

deps:
    WORKDIR /work
    CACHE --persist --sharing shared /go

    RUN apk add --no-cache gcc musl-dev
    DO go-ci+DEPS

src:
    FROM +deps

    COPY --dir cmd pkg .

check:
    FROM +src

    BUILD +fmt
    BUILD +lint

build:
    FROM +src

    ENV CGO_ENABLED=0
    RUN go mod tidy
    RUN go build -ldflags="-extldflags=-static" -o bin/updater cmd/main.go

    SAVE ARTIFACT bin/updater updater

test:
    FROM +build

    RUN ginkgo ./...

release:
    FROM +build

    SAVE ARTIFACT bin/updater updater

publish:
    FROM debian:bookworm-slim
    WORKDIR /workspace
    ARG tag=latest

    COPY +build/updater /usr/local/bin/updater

    ENTRYPOINT ["/usr/local/bin/updater"]
    SAVE IMAGE --push ci-updater:${tag}