VERSION 0.8

ARG REGISTRY="harbor.shared-services.projectcatalyst.io/dockerhub/library"
FROM ${REGISTRY}/golang:1.22.4-alpine3.20

IMPORT ../../earthly/go AS go-ci

# cspell: words onsi ldflags extldflags

fmt:
    DO go-ci+FMT --src="go.mod go.sum cmd pkg"

lint:
    DO go-ci+LINT --src="go.mod go.sum cmd pkg"

deps:
    WORKDIR /work
    CACHE --persist --sharing shared /go

    RUN apk add --no-cache gcc musl-dev
    DO go-ci+DEPS

src:
    FROM +deps

    COPY --dir cmd pkg .

check:
    FROM +src

    BUILD +fmt
    BUILD +lint

build:
    FROM +src

    ENV CGO_ENABLED=0
    RUN go mod tidy
    RUN go build -ldflags="-extldflags=-static" -o bin/fetcher cmd/main.go

    SAVE ARTIFACT bin/fetcher fetcher

test:
    FROM +build

    RUN ginkgo ./...

github:
    FROM +build

    SAVE ARTIFACT bin/fetcher fetcher

docker:
    FROM debian:bookworm-slim
    WORKDIR /workspace

    ARG container="jorm-fetcher"
    ARG tag="latest"

    COPY +build/fetcher /usr/local/bin/fetcher

    ENTRYPOINT ["/usr/local/bin/fetcher"]
    SAVE IMAGE --push ${container}:${tag}