VERSION 0.8

IMPORT ./../../../earthly/wasm/c AS wasm-c-ci

builder:
    FROM wasm-c-ci+wasm-c-base

    COPY demo.wit ./wit/
    COPY component.c .

# TODO: Enable when our earthly self-satellites will be back
disable-build: 
    FROM +builder

    RUN /scripts/std_build.py --c_files="component.c" --out="component.wasm"
    SAVE ARTIFACT component.wasm

