VERSION --global-cache 0.7

builder:
    FROM ./../../../earthly/wasm/c+wasm-c-base

    COPY demo.wit ./wit/
    COPY component.c .

build: 
    FROM +builder

    RUN /scripts/std_build.py --c_files="component.c" --out="component.wasm"
    RUN ls

