VERSION 0.8

IMPORT ../../earthly/python AS python-ci
IMPORT ../../earthly/container AS container

builder:
    FROM container+main-builder    
    COPY --dir pyproject.toml src . 

check:
    FROM +builder
    DO python-ci+CHECK

lint:
    FROM +builder
    DO python-ci+LINT --src=./src
