VERSION 0.8

# Assuming the detailed setup from the second snippet is defined in relevant Earthly targets.

builder:
    FROM ./../../earthly/python+python-base

    COPY --dir poetry.lock pyproject.toml Readme.md src .

check:
    FROM +builder

    DO ./../../earthly/python+CHECK

python-linter:
    FROM +builder
    
    DO ./../../earthly/python+LINT_PYTHON