# References to the rules 
# OpenAPI: https://docs.stoplight.io/docs/spectral/4dec24461f3af-open-api-rules#openapi-rules
# OWASP Top 10: https://apistylebook.stoplight.io/docs/owasp-top-10
# Documentations: https://github.com/stoplightio/spectral-documentation/blob/main/src/ruleset.ts

# cspell: words OWASP owasp

# Use CDN hosted version for spectral-documentation and spectral-owasp
extends:
- 'spectral:oas'
- 'https://unpkg.com/@stoplight/spectral-documentation@1.3.1/dist/ruleset.mjs'
- 'https://unpkg.com/@stoplight/spectral-owasp-ruleset@1.4.3/dist/ruleset.mjs'

formats: ["oas3", "json-schema-2020-12"]

rules: 
  api-path:
    message: "Invalid API path - should be /api/draft/* or /api/v<number>/*"
    given: "$.paths"
    severity: error
    then:
      field: "@key"
      function: pattern
      functionOptions:
        # Match paths that start with /api/draft/* or /api/v<number>/*
        match: "^/api/(draft|v\\d+)/.*$"
  api-content-type:
    message: "Content type must not be text/plain"
    given: "$.paths[*][*].responses[*].content"
    severity: error
    then:
      field: "@key"
      function: pattern
      functionOptions:
        # Match content type that is not text/plain
        match: "^(?!text/plain).*"
  api-content-type-json-object:
    message: "Content type application/json must be object"
    given: "$.paths[*][*].responses[*].content['application/json'].schema.type"
    severity: error
    then:
      field: "@value"
      function: pattern
      functionOptions:
        # Match content type application/json should be object
        match: "object"


# Ignoring rules example
# rules:
#   docs-tags: off
