# References to the rules 
# OepnAPI: https://docs.stoplight.io/docs/spectral/4dec24461f3af-open-api-rules#openapi-rules
# OWASP Top 10: https://apistylebook.stoplight.io/docs/owasp-top-10
# Documentations: https://github.com/stoplightio/spectral-documentation/blob/main/src/ruleset.ts

# Use CDN hosted version for spectral-documentation and spectral-owasp
extends:
- 'spectral:oas'
- 'https://unpkg.com/@stoplight/spectral-documentation/dist/ruleset.mjs'
- 'https://unpkg.com/@stoplight/spectral-owasp-ruleset/dist/ruleset.mjs'

# Ignoring rules
rules:
  docs-tags: off
