openapi: "3.0.2"
info:
servers:
- url: 'https://api.example.com'

paths:
  '/users':
    get:
      summary: Get a list of users
      responses:
        '200':
          headers:
            RateLimit-Limit:
              description: The number of allowed requests in the current period.
              schema:
                type: integer
                format: int32
                minimum: 1
                maximum: 1000
            RateLimit-Reset:
              description: The number of seconds left in the current period.
              schema:
                type: integer
                format: int32
                minimum: 1
                maximum: 1000
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                maxItems: 1000
                items:
                  $ref: '#/components/schemas/User'
    post:
      summary: Create a new user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          headers:
            RateLimit-Limit:
              description: The number of allowed requests in the current period.
              schema:
                type: integer
                format: int32
                minimum: 1
                maximum: 1000
            RateLimit-Reset:
              description: The number of seconds left in the current period.
              schema:
                type: integer
                format: int32
                minimum: 1
                maximum: 1000
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          headers:
            RateLimit-Limit:
              description: The number of allowed requests in the current period.
              schema:
                type: integer
                format: int32
                minimum: 1
                maximum: 1000
            RateLimit-Reset:
              description: The number of seconds left in the current period.
              schema:
                type: integer
                format: int32
                minimum: 1
                maximum: 1000
          description: Bad request
          content:
            application/json:
              example:
                message: "Invalid request payload"

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          minimum: 0
          maximum: 10000000
        username:
          type: string
          format: text
          maxLength: 10
        password:
          type: string
          format: password
          minLength: 8 # Rule: Password Length
          maxLength: 50
        email:
          type: string
          format: email
          maxLength: 20
        roles:
          type: array
          maxItems: 2
          items:
            type: string
            format: text
            maxLength: 255
          enum: ['user', 'admin'] # Rule: Role-Based Access Control (RBAC)

security:
- api_key: []

