name: CI Publish
description: Publishes the given Docker containers.
inputs:
  earthfile:
    description: Path to the Earthfile (excluding /Earthfile suffix) to build
    required: true
  earthly_satellite:
    description: The address of the remote Earthly satellite to use
    required: true
  images:
    description: A space seperated list of images the Earthfile will produce
    required: true
  registry:
    description: The registry to publish containers images to
    required: true
  tags:
    description: A space seperated list of tags to tag the resulting images with
  target:
    description: The target to build for the given Earthfile
    required: true

runs:
  using: composite
  steps:
    - name: Build
      shell: bash
      run: |
        earthly \
            --buildkit-host "tcp://${{ inputs.earthly_satellite }}:8372" \
            ${{ inputs.earthfile }}+${{ inputs.target }} \
            --tag=latest

          for image in ${{ inputs.images }}; do
            for tag in ${{ inputs.tags }}; do
              echo "Tagging ${image}:latest as ${{ inputs.registry }}/${image}:${tag}"
              docker tag "${image}:latest" "${{ inputs.registry }}/${image}:${tag}"

              echo "Pushing ${{ inputs.registry }}/${image}:${tag}"
              docker push "${{ inputs.registry }}/${image}:${tag}"
            done
          done
