VERSION 0.7
FROM golang:1.20-alpine3.18

# cspell: words onsi ldflags extldflags

deps:
    WORKDIR /work

    RUN apk add --no-cache gcc musl-dev
    DO ../earthly/go+DEPS

src:
    FROM +deps

    COPY --dir cmd pkg .

build:
    FROM +src

    ENV CGO_ENABLED=0
    RUN go build -ldflags="-extldflags=-static" -o bin/ci cmd/main.go

    SAVE ARTIFACT bin/ci ci

test:
    FROM +src

    RUN ginkgo ./...

docker:
    FROM debian:bookworm-slim
    WORKDIR /workspace

    COPY +build/ci /usr/local/bin/ci

    ENTRYPOINT ["/usr/local/bin/ci"]

fmt:
    DO ../earthly/go+FMT --src="go.mod go.sum cmd pkg"

lint:
    DO ../earthly/go+LINT --src="go.mod go.sum cmd pkg"

check:
    FROM +deps

    BUILD +fmt
    BUILD +lint

release:
    FROM +build

    SAVE ARTIFACT bin/ci ci

publish:
    FROM +docker
    ARG tag=latest

    SAVE IMAGE --push ci-cli:${tag}