VERSION 0.8
IMPORT ../earthly/go AS go-ci

FROM golang:1.22.4-alpine3.19

# cspell: words onsi ldflags extldflags

fmt:
    DO go-ci+FMT --src="go.mod go.sum cmd pkg"

lint:
    DO go-ci+LINT --src="go.mod go.sum cmd pkg"

deps:
    WORKDIR /work
    CACHE --persist --sharing shared /go

    RUN apk add --no-cache gcc musl-dev
    DO go-ci+DEPS

src:
    FROM +deps

    COPY --dir cmd pkg .

check:
    FROM +src

    BUILD +fmt
    BUILD +lint

build:
    FROM +src

    ENV CGO_ENABLED=0
    RUN go mod tidy
    RUN go build -ldflags="-extldflags=-static" -o bin/ci cmd/main.go

    SAVE ARTIFACT bin/ci ci

test:
    FROM +build
    
    RUN ginkgo ./...

release:
    FROM +build

    SAVE ARTIFACT bin/ci ci

publish:
    FROM debian:bookworm-slim
    WORKDIR /workspace
    ARG tag=latest

    COPY +build/ci /usr/local/bin/ci

    ENTRYPOINT ["/usr/local/bin/ci"]
    SAVE IMAGE --push ci-cli:${tag}