VERSION 0.8

IMPORT ../../../earthly/flutter AS flutter-ci
IMPORT ../../../earthly/flutter_rust_bridge AS flutter_rust_bridge

# To see more available functions, navigate to earthly/flutter/Earthfile.

# Set up the CI environment for Flutter app.
builder:
    DO flutter-ci+SETUP

    COPY --dir . .

# Run flutter analyze over melos analyze.
analyze:
    FROM +builder

    DO flutter-ci+ANALYZE

# Run dart format over melos format.
format:
    FROM +builder

    DO flutter-ci+FORMAT

# unit-tests - Run Flutter unit tests.
unit-tests:
    FROM +builder

    DO flutter-ci+UNIT_TESTS

# Build the Flutter app for the web.
# Assuming that we have a main.dart file in lib folder and we run `build-web` in folder
# with pubspec.yaml file: earthly +build-web --TARGET=lib/main.dart
build-web:
    FROM +builder

    ARG WORKDIR=/frontend
    ARG --required TARGET
    ARG --required SENTRY_DSN

    DO flutter-ci+BUILD_WEB --WORKDIR=$WORKDIR --TARGET=$TARGET --SENTRY_DSN=$SENTRY_DSN

# -----------------flutter_rust_bridge-----------------

builder-frb:
    FROM flutter_rust_bridge+builder
    COPY . .

# Generated necessary files for running Flutter web locally and save it locally.
code-generator-web:
    FROM +builder-frb
    DO flutter_rust_bridge+CODE_GENERATOR_WEB

    SAVE ARTIFACT ./assets/js AS LOCAL ./assets/js
    SAVE ARTIFACT ./rust/src/frb_generated.rs AS LOCAL ./rust/src/frb_generated.rs
    SAVE ARTIFACT ./lib/src AS LOCAL ./lib/src