VERSION --global-cache --use-function-keyword 0.7

# cspell: words bindgen autodrop mexec

wasm-c-base:
    FROM alpine:3.19
    WORKDIR /root

    RUN apk update && \
        apk add --no-cache \
        clang=17.0.5-r0 \
        lld=17.0.5-r0 \
        wasi-sdk=20-r3

    COPY ./../../rust+rust-base/wasm-tools /bin
    COPY ./../../rust+rust-base/wit-bindgen /bin

BUILD:
    FUNCTION
    ARG wit_path="wit"
    ARG --required c_files
    ARG output_file="component.wasm"

    RUN wit-bindgen c --autodrop-borrows yes $wit_path

    RUN clang demo.c demo_component_type.o $c_files -o out.wasm -mexec-model=reactor --target=wasm32-wasi

    RUN wasm-tools validate out.wasm && \
        wasm-tools component new out.wasm -o $output_file
