VERSION 0.8

IMPORT ../../rust/tools AS rust-tools
IMPORT ../../../utilities/scripts AS scripts

# cspell: words bindgen autodrop mexec

wasm-c-base:
    # This image comes from: 
    # https://github.com/WebAssembly/wasi-sdk/pkgs/container/wasi-sdk
    ARG REGISTRY="harbor.shared-services.projectcatalyst.io/ghcr"
    FROM ${REGISTRY}/webassembly/wasi-sdk:sha-400dd95
    WORKDIR /root

    RUN apt-get update && apt-get install -y \
        bash \
        build-essential \
        python3-rich \
        && rm -rf /var/lib/apt/lists/*

    COPY rust-tools+tool-wasm-tools/wasm-tools /bin
    COPY rust-tools+tool-wit-bindgen/wit-bindgen /bin

    # Universal build scripts.
    COPY --dir scripts /scripts
    # Copy our common scripts so we can use them inside the container.
    DO scripts+ADD_BASH_SCRIPTS
    DO scripts+ADD_PYTHON_SCRIPTS
