VERSION --global-cache 0.7

wasm-c-base:
    FROM alpine:3.19
    WORKDIR /repo

    RUN apk update && \
        apk add --no-cache \
        clang=17.0.5-r0 \
        lld=17.0.5-r0 \
        wasi-sdk=20-r3

BUILD:
    FUNCTION
    ARG --required wit_path
    ARG --required c_files
    ARG output_file="out.wasm"
    ARG component_file="component.wasm"

    RUN wit-bindgen c --autodrop-borrows yes $wit_path

    RUN clang hermes.c hermes_component_type.o $c_files -o $output_file -mexec-model=reactor --target=wasm32-wasi

    RUN wasm-tools validate $output_file && \
        wasm-tools component new $output_file -o $component_file

example:
    FROM +wasm-c-base

    COPY ../wasi/wit .
    COPY my-component.c .

    DO +BUILD --wit_path="wasi/wit" --c_files="my-component.c"
