name: CI Deploy
description: Deploys the published images to the remote cluster.
inputs:
  deployment_repo:
    description: The URL of the repository containing deployment code
    required: true
  discover_output:
    description: The output from the discover step
    required: true
  environment:
    description: The target environment to deploy to
    required: true
  tag:
    description: The image tag to deploy
    required: true
  token:
    description: Github token for accessing deployment repo
    required: true

runs:
  using: composite
  steps:
    - name: Checkout deployment repository
      uses: actions/checkout@v3
      with:
        repository: ${{ inputs.deployment_repo }}
        ref: deployment # TODO: Remove me
        token: ${{ inputs.token }}
    - name: Update deployment hashes
      shell: bash
      id: discover
      run: |
        UPDATED=$(echo '${{ inputs.discover_output }}' | jq -cr 'map({(.images | split(" ")[] ): "${{ inputs.tag }}"}) | add')
        echo "${UPDATED}" > updated.json

        ls -la

        echo "Current:"
        cat src/kube/environments/${{ inputs.environment }}/hashes.json

        echo "Updated:"
        cat updated.json

        HASHES=src/kube/environments/${{ inputs.environment }}/hashes.json
        jq -s '.[0] * .[1]' "$HASHES" updated.json > "$HASHES"

        echo "Updated hashes:"
        cat "$HASHES"
