# cspell: words cibot

name: CI Deploy
description: Deploys the published images to the remote cluster.
inputs:
  deployment_repo:
    description: The URL of the repository containing deployment code
    required: false
    default: "https://github.com/input-output-hk/catalyst-world"
  environment:
    description: The target environment to deploy to
    required: true
  hash_file:
    description: The relative path to the hash file to update with deployment information
    required: true
  images:
    description: A space separated list of image names to deploy
    required: true
  tag:
    description: The image tag to deploy
    required: true
  token:
    description: Github token for accessing deployment repo
    required: true

runs:
  using: composite
  steps:
    - name: Checkout deployment repository
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.deployment_repo }}
        token: ${{ inputs.token }}
    - name: Update deployment hashes
      shell: bash
      id: discover
      run: |
        CHANGES=$(jq -n "$(for img in ${{ inputs.images }}; do printf '."%s"="%s" | ' $img "${{ inputs.tag }}"; done) .")
        echo "${CHANGES}" > /tmp/changes.json

        HASHES=src/kube/environments/${{ inputs.environment }}/hashes.json
        FINAL=$(jq -s '.[0] * .[1]' "$HASHES" /tmp/changes.json)
        echo "$FINAL" > "$HASHES"

        git --no-pager diff

        REPO_NAME=$(echo '${{ github.repository }}' | cut -d '/' -f 2)
        git config --global user.email "ci@projectcatalyst.io"
        git config --global user.name "catalyst-cibot"
        git add "$HASHES"
        git commit -m "chore: updates $REPO_NAME deployments"
        git push origin "$(git rev-parse --abbrev-ref HEAD)"
