VERSION --global-cache 0.7 

# cspell: words ruleset

spectral-base:
    FROM busybox
    COPY . .
    RUN ls
    # COPY ./earthly/spectral/minify-json.sh minify-json.sh
    RUN chmod +x ./minify-json.sh
    RUN ls
    SAVE ARTIFACT minify-json.sh

BUILD_SPECTRAL:
    COMMAND

    # Specify what file type to lint 
    ARG file_type = "json"
    ARG dir = .
    ARG src = .
    # Rule set for spectral
    ARG rule_set=.spectral.yml

    FROM stoplight/spectral
    WORKDIR /work
    COPY $src .

    RUN ls    
    COPY +spectral-base/minify-json.sh minify-json.sh

    # If file type is json, minify the JSON
    RUN ./minify-json.sh

    RUN spectral \
        lint \
        $dir/"**/*.{yml,json}" \
        --ruleset $rule_set