VERSION 0.8

# cspell: words ruleset

spectral-base:
    FROM harbor.shared-services.projectcatalyst.io/dockerhub/library/stoplight/spectral:6.13.1
    WORKDIR /work

LINT:
    FUNCTION
    
    # FIle type to be linted, default linting only JSON files
    ARG file_type = json
    # Directory to lint
    ARG dir = .
    # Rule set for spectral
    ARG rule_set = .spectral.yml

    RUN spectral \
        lint \
        $dir/"**/*.$file_type" \
        --ruleset $rule_set 
