VERSION 0.8

IMPORT github.com/input-output-hk/catalyst-ci/earthly/python:v3.1.7 AS python-ci

check:
    FROM python-ci+python-base

    COPY . .

    DO python-ci+CHECK

# convert - converts cql files into d2 diagram entity files
convert:
    FROM python-ci+python-base

    ARG --required input
    ARG --required output

    COPY . .

    RUN python3 main.py $input $output

    SAVE ARTIFACT $output
