# cspell UDCs and Containers.
VERSION 0.7

CSPELL:
    # Spell checking all docs and code is done with cspell
    # See: cspell.org
    COMMAND

    # Where we want to run the `lint` from.
    ARG --required src

    # Unlikely to need to change this.
    ARG cfg_file=cspell.json

    RUN --no-cache if [[ ! -f $src/$cfg_file ]]; then \
        (>&2 echo "$src/$cfg_file does not exist. Can not check spelling."); \
        exit 1; \
    fi

    RUN --no-cache echo Spell Checking Recursively from: $src

    WITH DOCKER --pull ghcr.io/streetsidesoftware/cspell:latest
        RUN --no-cache \
            docker run \
            --rm \
            -v $src:/workdir \
            ghcr.io/streetsidesoftware/cspell:latest \
            lint .
    END

# A Test and example invocation of the above UDC.
cspell-test:
    # Test spellcheck lint checks.
    # Run with `earthly -P +cspell-test
    LOCALLY

    DO +CSPELL --src=$(echo ${PWD}/../../)

