VERSION 0.8

IMPORT github.com/input-output-hk/catalyst-ci/earthly/python:v3.1.7 AS python-ci

check:
    FROM python-ci+python-base

    COPY . .

    DO python-ci+CHECK

src:
    FROM scratch

    COPY . .

    SAVE ARTIFACT main.py