name: CI Discovery
description: Discovers Earthfiles in the given paths and compiles data about them
inputs:
  parse_images:
    description: Whether the image names from the given targets should be returnd (requires at least one target)
    required: false
    default: "false"
  paths:
    description: A space separated list of paths to search
    required: false
    default: "."
  targets:
    description: A space seperated list of targets to filter against
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Discover
      shell: bash
      id: discover
      run: |
        FLAGS=("-j")

        if [[ "${{ inputs.parse_images }}" == "true" ]]; then
          FLAGS+=("-i")
        fi

        for target in ${{ inputs.targets }}; do
          FLAGS+=("-t" "$target")
        done

        JSON_OUTPUT=$(ci scan "${FLAGS[@]}" ${{ inputs.paths }})
        echo "$JSON_OUTPUT"
