VERSION 0.8

IMPORT ../python AS python-ci
IMPORT ../../utilities/scripts AS scripts

# cspell: words freetype lcms openjpeg etag

deps:
    FROM python-ci+python-base
    # Derived from official mkdocs-material docker container.
    # https://github.com/squidfunk/mkdocs-material/blob/master/Dockerfile
    # Due to docs being constructed not only from Doc source but Build artifacts,
    # These docs do NOT support Live serving, and must be built.
    # This is all the tooling needed to build the docs.

    # Install extra packages we will need to support plugins.
    RUN apk add --no-cache \
        bash \
        graphviz \
        fontconfig \
        ttf-liberation \
        curl \
        zlib-dev \
        jpeg-dev \
        libxml2-dev \
        libxslt-dev \
        libffi-dev \
        gcc \
        musl-dev \
        libgcc \
        openssl-dev \
        freetype-dev \
        lcms2-dev \
        openjpeg-dev \
        tiff-dev \
        tk-dev \
        tcl-dev  \
        git \
        make

    # Fix up font cache
    RUN fc-cache -f

    # Install D2
    RUN curl -fsSL https://d2lang.com/install.sh | sh -s --

    # Install poetry and our python dependencies.
    DO python-ci+BUILDER --opts=--no-root

    # Copy our run scripts
    COPY --dir scripts/* /scripts/
    # Copy our common scripts so we can use them inside the container.
    DO scripts+ADD_BASH_SCRIPTS

    # Trust directory, required for git >= 2.35.2. (mkdocs Git plugin requirement).
    RUN git config --global --add safe.directory /docs &&\
        git config --global --add safe.directory /site

    # Set working directory
    WORKDIR /docs


# Documentation files used across all documentation builds.
common:
    FROM scratch

    COPY --dir common/includes common/macros common/overrides common/std-theme.yml /std

    SAVE ARTIFACT /std

# The file we use for local-docs:
local-docs:
    FROM scratch

    COPY dev .
    SAVE ARTIFACT dev

# SYNC_STD_CFG : Syncs the standard config files locally.
SYNC_LOCAL_DOCS:
    FUNCTION
    FROM +local-docs

    SAVE ARTIFACT /dev/local.py AS LOCAL local.py

# Common src setup
SRC:
    FUNCTION

    FROM +deps

    # Copy Common documentation files.
    COPY +common/* .

    # Just copy the actual doc src here.
    COPY --dir src mkdocs.yml .

    # Any files which replace the standard files are copied here
    COPY --if-exists --dir includes macros overrides .


# Build the docs - We always do this in a `docs` target.  
# The only target that needs customizing is the `src` target.
BUILD:
    FUNCTION

    RUN /scripts/build.sh

    SAVE ARTIFACT /site/*


# See `<repo>/docs` for the example docs project which uses this tooling.

# Docs fall outside the normal CI flow and have their own build and publish flow.

# We do however build a docs package which is used for locally serving the docs
# which assists in documentation writing.
PACKAGE:
    FUNCTION

    # Use the official Nginx base image
    FROM nginx:alpine3.20-slim

    # Force this server to disable the browsers cache for these files.
    RUN echo " " > /etc/nginx/conf.d/disable-cache.conf; \
        echo "    add_header Last-Modified \$date_gmt;" >> /etc/nginx/conf.d/disable-cache.conf; \
        echo "    add_header Cache-Control 'private no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';" >> /etc/nginx/conf.d/disable-cache.conf; \
        echo "    if_modified_since off;" >> /etc/nginx/conf.d/disable-cache.conf; \
        echo "    expires off;" >> /etc/nginx/conf.d/disable-cache.conf; \
        echo "    etag off;" >> /etc/nginx/conf.d/disable-cache.conf;

    # Expose port 80 for HTTP traffic
    EXPOSE 80

    # Start Nginx when the container is run
    CMD ["nginx", "-g", "daemon off;"]

    # These steps are done outside the FUNCTION.

    # Copy the static pages into the container like this...
    #COPY $docs /usr/share/nginx/html

    # And then save the image
    # SAVE IMAGE image_name
    
