VERSION --global-cache 0.7

# Copy all the source we need to build the docs
src:
    # Common src setup
    DO ../earthly/docs+SRC

    # Now copy into that any artifacts we pull from the builds.
    COPY --dir ../+repo-docs/repo includes

    # Copy docs we build in the postgres example.
    COPY --dir ../examples/postgresql+build/docs src/appendix/examples/built_docs/postgresql

# Build the docs here.
docs:
    FROM +src

    DO ../earthly/docs+BUILD


# Make a docker image that can serve the docs for development purposes.
# This target is only for local developer use.
local:
    DO ../earthly/docs+PACKAGE

    COPY +docs/ /usr/share/nginx/html

    SAVE IMAGE cat-ci-docs:latest