sample_table: {
	shape: sql_table
	tooltip: |md

	|

	column_name_1: (int) {constraint: [K]}
	column_name_2: (int) {constraint: [P↑]}
	column_name_3: (int) {constraint: [P↓]}
	column_name_4: (text) {constraint: [S]}
	column_name_5: (int)
	column_name_6: (bigint) {constraint: [++]}
	"[column_name_7]": (int)
	"{column_name_8}": (int)
	"<column_name_9>": (int)
	"*column_name_10*": (custom_int)
	"(column_name_11)": (int, set<int>)
	column_name_12: (int)
}