VERSION 0.8

# cspell: words amazoncorretto corretto

# Base image for Java used in other targets to avoid improve caching
java-base:
    FROM harbor.shared-services.projectcatalyst.io/dockerhub/amazoncorretto:21-al2023-jdk

    SAVE ARTIFACT /usr/lib/jvm/java-21-amazon-corretto.x86_64 /java

COPY_DEPS:
    FUNCTION
    COPY +java-base/java /usr/local/openjdk-21

    # Set environment variables for Java
    ENV JAVA_HOME=/usr/local/openjdk-21
    ENV PATH=$JAVA_HOME/bin:$PATH
