VERSION 0.8

# cspell: words Chromedriver Edgedriver edgedriver msedgedriver Geckodriver geckodriver

# Install Chrome/Chromium for testing and Chromedriver.
# There is no Chrome-for-testing build for linux/arm64, using Chromium instead.
# https://github.com/GoogleChromeLabs/chrome-for-testing/issues/1
INSTALL_CHROME_LINUX64:
    FUNCTION
    ARG TARGETARCH
    LET BLUE ='\033[0;34m'

    # https://googlechromelabs.github.io/chrome-for-testing/
    # Stable version: https://www.ubuntuupdates.org/package/google_chrome/stable/main/base/google-chrome-stable
    IF [ "$TARGETARCH" = "amd64" ]
        ARG --required chrome_version
        
        # Install Google Chrome
        RUN printf "${BLUE} Installing Google Chrome..."
        RUN curl -sSL -o /opt/chrome.deb https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${chrome_version}-${chrome_package_release}_amd64.deb \
            && apt install -y /opt/chrome.deb \
            && rm /opt/chrome.deb \
            && mv /usr/bin/google-chrome-stable /usr/bin/google-chrome
        RUN google-chrome --version

        # Install Chromedriver
        RUN printf "${BLUE} Installing Chromedriver..."
        RUN mkdir -p /opt/chromedriver
        RUN curl -L https://storage.googleapis.com/chrome-for-testing-public/${chrome_version}/linux64/chromedriver-linux64.zip \
            -o /opt/chromedriver/chromedriver.zip \
            && unzip -j /opt/chromedriver/chromedriver.zip -d /usr/local/bin/
        RUN chromedriver --version

    ELSE 
        # Chromium source: https://packages.debian.org/source/bookworm/chromium
        ARG --required chromium_version
        # Install Chromium
        RUN printf "${BLUE} Installing Chromium..."
        RUN curl -sSL -o /opt/chromium.deb http://security.debian.org/debian-security/pool/updates/main/c/chromium/chromium_${chromium_version}_arm64.deb \
            && apt install -y /opt/chromium.deb \
            && rm /opt/chromium.deb \
            && mv /usr/bin/chromium /usr/bin/google-chrome
        RUN google-chrome --version

        # Install Chromium-driver
        RUN printf "${BLUE} Installing Chromium-driver..."
        RUN curl -sSL -o /opt/chrome-driver.deb http://security.debian.org/debian-security/pool/updates/main/c/chromium/chromium-driver_${chromium_version}_arm64.deb \
            && apt install -y /opt/chrome-driver.deb \
            && rm /opt/chrome-driver.deb
        RUN chromedriver --version
    END

# Install Edge and EdgeDriver.
# There is no Edge version build for linux/arm64, installing only for amd64.
INSTALL_EDGE_LINUX64:
    FUNCTION
    ARG TARGETARCH
    LET BLUE ='\033[0;34m'

    IF [ "$TARGETARCH" = "amd64" ]
        ARG --required edge_version
        ARG --required edge_package_release

        RUN printf "${BLUE} Installing Edge..."
        RUN curl -LO https://packages.microsoft.com/repos/edge/pool/main/m/microsoft-edge-stable/microsoft-edge-stable_${edge_version}-${edge_package_release}_amd64.deb
        RUN apt-get update && apt-get install -y ./microsoft-edge-stable_${edge_version}-${edge_package_release}_amd64.deb
        RUN microsoft-edge-stable --version

        # https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver
        RUN printf "${BLUE} Installing Edgedriver..."
        RUN mkdir -p /opt/edgedriver
        RUN curl -L https://msedgedriver.azureedge.net/{$edge_version}/edgedriver_linux64.zip \
            -o /opt/edgedriver/edgedriver.zip
        RUN unzip /opt/edgedriver/edgedriver.zip -d /usr/local/bin/
        RUN msedgedriver --version
    END

# Install Firefox and Geckodriver. 
# Geckodriver supported versions:
# https://firefox-source-docs.mozilla.org/testing/geckodriver/Support.html
INSTALL_FIREFOX_LINUX64:
    FUNCTION
    ARG TARGETARCH
    LET PLATFORM = ""
    LET BLUE ='\033[0;34m'

    RUN printf "${BLUE} Installing Firefox..."
    WAIT
        RUN install -d -m 0755 /etc/apt/keyrings
        RUN curl -fSsL https://packages.mozilla.org/apt/repo-signing-key.gpg \
            | tee /etc/apt/keyrings/packages.mozilla.org.asc > /dev/null
        RUN echo "deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main" \
            | tee -a /etc/apt/sources.list.d/mozilla.list > /dev/null
        RUN echo "Package: *\nPin: origin packages.mozilla.org\nPin-Priority: 1000\n\n" \
            | tee /etc/apt/preferences.d/mozilla > /dev/null
    END
    
    IF [ "$TARGETARCH" = "amd64" ]
        SET PLATFORM = linux64
        ARG --required firefox_version_amd64
        RUN apt-get update && apt-get install -y -t mozilla firefox=${firefox_version_amd64}
    ELSE
        SET PLATFORM = linux-aarch64
        ARG --required firefox_version_arm64
        RUN apt-get update && apt-get install -y -t mozilla firefox-esr=${firefox_version_arm64}
    END

    RUN firefox --version
    
    RUN printf "${BLUE} Installing Geckodriver..."
    RUN mkdir -p /opt/geckodriver
    ARG --required gecko_version
    RUN curl -sL https://github.com/mozilla/geckodriver/releases/download/v${gecko_version}/geckodriver-v${gecko_version}-${PLATFORM}.tar.gz \
        | tar -xz -C /opt/geckodriver/
    RUN ln -s /opt/geckodriver/geckodriver /usr/local/bin/geckodriver
    RUN geckodriver --version
