VERSION 0.8

IMPORT github.com/earthly/lib/rust:3.0.2 AS rust

tool-cargo-nextest:
    FROM ../+rust-base
    DO rust+CARGO --args="install cargo-nextest --version=0.9.68 --locked"
    
    SAVE ARTIFACT /usr/local/cargo/bin/cargo-nextest cargo-nextest


tool-cargo-machete:
    FROM ../+rust-base
    DO rust+CARGO --args="install cargo-machete --version=0.6.2 --locked"
    SAVE ARTIFACT /usr/local/cargo/bin/cargo-machete cargo-machete

tool-refinery:
    FROM ../+rust-base
    DO rust+CARGO --args="install refinery_cli --version=0.8.14 --locked"
    SAVE ARTIFACT /usr/local/cargo/bin/refinery refinery

tool-cargo-deny:
    FROM ../+rust-base
    DO rust+CARGO --args="install cargo-deny --version=0.14.10 --locked"
    SAVE ARTIFACT /usr/local/cargo/bin/cargo-deny cargo-deny

tool-cargo-modules:
    FROM ../+rust-base
    DO rust+CARGO --args="install cargo-modules --version=0.14.0 --locked"
    SAVE ARTIFACT /usr/local/cargo/bin/cargo-modules cargo-modules

tool-cargo-depgraph:
    FROM ../+rust-base
    DO rust+CARGO --args="install cargo-depgraph --version=1.6.0 --locked"
    SAVE ARTIFACT /usr/local/cargo/bin/cargo-depgraph cargo-depgraph

tool-cargo-llvm-cov:
    FROM ../+rust-base
    DO rust+CARGO --args="install cargo-llvm-cov --version=0.6.9 --locked"
    SAVE ARTIFACT /usr/local/cargo/bin/cargo-llvm-cov cargo-llvm-cov

tool-wasm-tools:
    FROM ../+rust-base
    DO rust+CARGO --args="install wasm-tools --version=1.203.0 --locked"
    SAVE ARTIFACT /usr/local/cargo/bin/wasm-tools wasm-tools

tool-cargo-expand:
    FROM ../+rust-base
    DO rust+CARGO --args="install cargo-expand --version=1.0.82 --locked"
    SAVE ARTIFACT /usr/local/cargo/bin/cargo-expand cargo-expand

tool-wit-bindgen-cli:
    FROM ../+rust-base
    DO rust+CARGO --args="install wit-bindgen-cli --version=0.24.0 --locked"
    SAVE ARTIFACT /usr/local/cargo/bin/wit-bindgen wit-bindgen

tool-wasmtime:
    FROM ../+rust-base
    DO rust+CARGO --args="install --git https://github.com/bytecodealliance/wasmtime --tag v17.0.0 verify-component-adapter --locked"
    SAVE ARTIFACT /usr/local/cargo/bin/verify-component-adapter verify-component-adapter
