[package]
name = "core"
version = "2.0.0-beta"
authors = ["Abid Omar <contact@omarabid.com>"]
description = "The application core code"
edition = "2021"

[dependencies]
utils = { path = "../utils" }

rand = "0.8.4"
log = "0.4.14"
