VERSION 0.7

# cspell: words preprod

package-preprod-snapshot:
    FROM alpine:3.19

    WORKDIR /snapshot

    RUN wget -O \
        preprod.tar.zst \
        https://storage.googleapis.com/cdn.aggregator.release-preprod.api.mithril.network/preprod-e135-i2625.80b0c02cd0c86c47a79a9b6d0d9b0e6936d5f621e8094ed53405fef3ee103a3b.tar.zst

    # extract preprod archive
    RUN apk add zstd
    RUN zstd -d preprod.tar.zst && tar -xf preprod.tar
    RUN rm preprod.tar && rm preprod.tar.zst

    SAVE ARTIFACT /snapshot snapshot