VERSION 0.8

# cspell: words preprod

base-snapshot-builder:
    # Note: an official docker image is here, but it could not reliably pull from Earthly.
    # It gives permission denied errors randomly.
    # Image comes from: https://github.com/input-output-hk/mithril/pkgs/container/mithril-client
    # FROM ghcr.io/input-output-hk/mithril-client:latest

    # Build our own simple mithril client image
    FROM debian:stable-20240408-slim
    