# WARNING: If you modify this file, please update the guide that it is dependent
# on in docs/guides/languages/go.md.
VERSION 0.8

IMPORT ../../earthly/go AS go-ci

# The structure of this Earthfile is derived from the style guide:
# https://input-output-hk.github.io/catalyst-ci/style/#adhere-to-a-consistent-structure

deps:
    # This target is used to install external Go dependencies.
    FROM golang:1.22.4-alpine3.20
    WORKDIR /work

    # Any build dependencies should also be captured in this target.
    RUN apk add --no-cache gcc musl-dev

    # This FUNCTION automatically copies the go.mod and go.sum files and runs
    # `go mod download` to install the dependencies.
    DO go-ci+DEPS --ginkgo="false"

src:
    # This target copies the source code into the current build context
    FROM +deps

    COPY --dir cmd .

check:
    # This target checks the overall health of the source code.
    FROM +src

    # This FUNCTION validates the code is formatted according to Go standards.
    DO go-ci+FMT --src="go.mod go.sum cmd"

    # This FUNCTION runs golangci-lint to check for common errors.
    DO go-ci+LINT --src="go.mod go.sum cmd"

build:
    # This target builds the application.
    FROM +src

    # The below just creates a fully static binary with no CGO dependencies.
    ENV CGO_ENABLED=0
    RUN go mod tidy
    RUN go build -ldflags="-extldflags=-static" -o bin/hello cmd/main.go

    # We save the artifact here so that future targets can use it.
    SAVE ARTIFACT bin/hello hello

test:
    # This target runs unit tests.
    FROM +build

    RUN go test ./...
