# cspell UDCs and Containers.
VERSION --global-cache  0.7

# Internal: builder creates a container we can use to execute shellcheck
builder:
    FROM alpine:3.18

    RUN apk add --no-cache \
        bash \
        shellcheck \
        shfmt

    WORKDIR /work
    COPY check-all.sh shellcheck-dir.sh duplicated-scripts.sh .

    # Copy our common scripts so we can use them inside the container.
    # Internally in the repo we use a symlink to accomplish this, but Earthly
    # Will only copy the symlink and not what it references, so we need to
    # manually copy what it references.  This enables the script to work
    # both in-repo and in-ci here.
    DO ../../utilities/scripts+ADD_BASH_SCRIPTS

# shellcheck - Check all shell files recursively in the src with shellcheck.
SHELLCHECK:
    COMMAND
    ARG --required src

    FROM +builder

    COPY --dir $src /src

    RUN ./check-all.sh /src

