VERSION 0.7

FMT:
    COMMAND

    FROM cytopia/gofmt:latest
    WORKDIR /work

    ARG --required src

    FOR f IN ${src}
        COPY ${f} /work/${f}
    END

    RUN gofmt -l . | grep . && exit 1 || exit 0

LINT:
    COMMAND

    FROM golangci/golangci-lint:latest
    WORKDIR /work

    ARG --required src

    FOR f IN ${src}
        COPY ${f} /work/${f}
    END

    RUN golangci-lint run \
        -E errchkjson \
        -E ginkgolinter \
        -E godot \
        -E goimports \
        -E gosec \
        -E nilnil \
        -E revive \
        -E testpackage