# cspell: words Zwasm

VERSION 0.8

IMPORT ../flutter AS flutter-ci
IMPORT ../rust AS rust-ci
IMPORT ../debian AS debian

# This will be refactored in the future
# TODO(bkioshn): https://github.com/input-output-hk/catalyst-ci/issues/322
# builder: Setup necessary tools for `flutter_rust_bridge`
builder:
    FROM debian+common

    DO debian+INSTALL --packages=clang

    WORKDIR /work

    DO flutter-ci+INSTALL_FLUTTER
    DO rust-ci+INSTALL_RUST
    DO rust-ci+INSTALL_TOOLS

# Generated necessary files for running Flutter web.
CODE_GENERATOR_WEB:
    FUNCTION
    ARG --required WASM_MODULE_NAME
    ARG RELEASE_MODE=false

    LET ADDITIONAL_BUILD_ARGS = ""

    IF [ $RELEASE_MODE = true ]
        SET ADDITIONAL_BUILD_ARGS = "$ADDITIONAL_BUILD_ARGS --release"
    END

    # TODO(dt-iohk): revert to official version when changes from the fork are merged into the official version
    GIT CLONE --branch feat/wasm-bindgen-configurable-module https://github.com/input-output-hk/catalyst_flutter_rust_bridge.git /usr/local/flutter_rust_bridge
    RUN cargo run --manifest-path /usr/local/flutter_rust_bridge/frb_codegen/Cargo.toml -- generate
    RUN cargo run --manifest-path /usr/local/flutter_rust_bridge/frb_codegen/Cargo.toml -- build-web \
        --wasm-bindgen-args="--no-modules-global=$WASM_MODULE_NAME" \
        --wasm-pack-rustflags "-Ctarget-feature=+atomics -Clink-args=--shared-memory -Clink-args=--max-memory=1073741824 -Clink-args=--import-memory -Clink-args=--export=__wasm_init_tls -Clink-args=--export=__tls_size -Clink-args=--export=__tls_align -Clink-args=--export=__tls_base" \
        $ADDITIONAL_BUILD_ARGS

    # RUN flutter_rust_bridge_codegen generate
    # RUN flutter_rust_bridge_codegen build-web \
    #    --wasm-bindgen-args="--no-modules-global=$WASM_MODULE_NAME" \
    #    --wasm-pack-rustflags "-Ctarget-feature=+atomics -Clink-args=--shared-memory -Clink-args=--max-memory=1073741824 -Clink-args=--import-memory -Clink-args=--export=__wasm_init_tls -Clink-args=--export=__tls_size -Clink-args=--export=__tls_align -Clink-args=--export=__tls_base" \
    #    $ADDITIONAL_BUILD_ARGS \

    RUN mkdir -p assets/js && cp -rf ./web/pkg/* assets/js/
     # Don't want this gitignore file.
    RUN rm -rf ./assets/js/.gitignore

    # Reformat code once it's generated under lib directory.
    RUN dart format lib
