name: "Run"
description: "Runs an Earthly target"
inputs:
  artifact:
    description: If true, forces artifacts to be saved locally
    required: false
    default: "false"
  artifact_path:
    description: The path (relative to earthfile) where artifacts will be placed
    required: false
    default: out
  earthfile:
    description: The path to the Earthfile containing the target to run
    required: true
  flags:
    description: Additional flags to pass to the Earthly CLI
    required: false
  platform:
    description: The platform to execute the earthfile target with (defaults to native)
    required: false
  privileged:
    description: Whether the workflow should run earthly in privileged mode (earthly -P flag).
    required: false
    default: "false"
  runner_address:
    description: The address of the remote runner to use
    required: false
  runner_port:
    description: The port to use for connecting to the remote runner
    required: false
    default: "8372"
  target:
    description: The name of the target to run
    required: true
  target_flags:
    description: Additional flags to pass to the target
    required: false
runs:
  using: "node20"
  main: "dist/index.js"
