VERSION 0.8

deps:
    FROM node:20-bookworm
    WORKDIR /work

    COPY package.json package-lock.json .
    RUN npm ci

src:
    FROM +deps

    COPY --dir src src
    COPY .eslintrc.yml tsconfig.json .

build:
    FROM +src

    RUN npm run package

    SAVE ARTIFACT dist dist AS LOCAL dist

test:
    FROM +build

    RUN npm test

    # Verify the package is not out of date
    COPY --dir dist dist_old
    RUN npm run package
    RUN diff -r dist_old dist

check:
    FROM +src

    RUN npm run format:check
    RUN npm run lint

nightly:
    FROM +test

    # Generate test report
    RUN npm test -s --junitxml=test-report.xml

    # Generate coverage report
    RUN npm test -- --coverage

    SAVE ARTIFACT ./test-report.xml AS LOCAL test-report/test-report.xml
    SAVE ARTIFACT ./coverage/lcov-report AS LOCAL coverage-report
