VERSION 0.8

IMPORT ../debian AS debian

# Define a constant name for the container and its version.
ARG --global CUE_VERSION=0.14.2
ARG --global CUE_IMAGE="harbor.shared-services.projectcatalyst.io/dockerhub/cuelang/cue:${CUE_VERSION}"


INSTALL:
    FUNCTION

    COPY +cue-bin/cue /usr/bin/cue
    RUN cue version

# Get cue binary
cue-bin:
    FROM $CUE_IMAGE
    SAVE ARTIFACT /usr/bin/cue

# Just check that Cue can be properly installed, and runs.
check-cue:
    FROM debian+common
    
    DO +INSTALL

    RUN cue version
