VERSION 0.8

# IMPORT ../debian AS debian
IMPORT ../chainguard AS chainguard

# Define a constant name for the container and its version.
ARG --global CUE_IMAGE="harbor.shared-services.projectcatalyst.io/dockerhub/cuelang/cue:0.14.1"


INSTALL:
    FUNCTION

     COPY +cue-bin/cue /usr/bin/cue


# Get cue binary
cue-bin:
    FROM $CUE_IMAGE
    SAVE ARTIFACT /usr/bin/cue

# Just check that Cue can be properly installed, and runs.
check-cue:
    # FROM debian+common
    FROM chainguard+common
    
    DO +INSTALL

    RUN cue version