name: Install
description: Installs the Catalyst-CI CLI
inputs:
  token:
    description: Github token used to query API for available CLI releases
    required: false
    default: ${{ github.token }}
  version:
    description: The version of the Catalyst-CI CLI to install
    required: false
    default: latest
  local:
    description: Use the local Catalyst-CI CLI
    required: false
    default: 'true'
runs:
  using: node20
  main: dist/index.js
