name: Install
description: Installs the Catalyst-CI CLI
inputs:
  asset:
    description: Which asset to install from the Catalyst-CI repository
    required: false
    default: cli
  token:
    description: Github token used to query API for available CLI releases
    required: false
    default: ${{ github.token }}
  version:
    description: The version of the Catalyst-CI CLI to install
    required: false
    default: latest
runs:
  using: node20
  main: dist/index.js
