[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version= "4.4.7", features = ["derive" ] }

[dev-dependencies]

[[test]]
name = "integration_test"
harness = false

[[bench]]
name = "benchmark"
