VERSION 0.7

deps:
    FROM python:3.12.0rc3-slim-bookworm
    WORKDIR /work

    ARG version = 1.7.1

    ENV POETRY_HOME=/tmp/poetry
    ENV PATH=$POETRY_HOME/bin:$PATH

    RUN apt-get update && \
        apt-get install -y --no-install-recommends curl

    RUN curl -sSL https://install.python-poetry.org | POETRY_VERSION=$version python3 -

    COPY pyproject.toml .
    COPY poetry.lock .

    RUN poetry install --only main --no-root

src:
    FROM +deps

    COPY --dir jorm-metrics-server .

check:
    FROM +src

    RUN poetry install --only dev --no-root
    RUN poetry run ruff check .
    RUN poetry run ruff format --check .