name: CI Deployment Setup
description: Performs required steps to setup CI for deploying to Kubernetes environments.
inputs:
  environment:
    description: The target environment to configure deployment for
    required: true
  state_bucket:
    description: The name of the S3 bucket holding remote Terraform state.
    required: true
runs:
  using: composite
  steps:
    - name: Install Tanka
      shell: bash
      run: |
        sudo curl -fSL -o /usr/local/bin/tk "https://github.com/grafana/tanka/releases/download/v0.25.0/tk-linux-amd64"
        sudo chmod +x /usr/local/bin/tk
    - name: Configure cluster access
      shell: bash
      run: |
        CLUSTER_STATE=$(ci state -b ${{ inputs.state_bucket }} -e ${{ inputs.environment }} kubernetes/cluster)
        CLUSTER_NAME=$(echo "${CLUSTER_STATE}" | jq -r .cluster_name.value)
        CLUSTER_REGION=$(echo "${CLUSTER_STATE}" | jq -r .cluster_arn.value | cut -d ":" -f 4)

        aws eks --region "${CLUSTER_REGION}" update-kubeconfig --name "${CLUSTER_NAME}"
