name: CI Setup
description: Performs required steps to setup CI
inputs:
  cli_version:
    description: The version of the CI CLI to install
    required: false
    default: 0.0.1
  earthly_version:
    description: The version of Earthly to install
    required: false
    default: latest
runs:
  using: composite
  steps:
    - name: Install Earthly
      uses: earthly/actions-setup@v1
      with:
        version: ${{ inputs.earthly_version }}
    - name: Install CLI
      shell: bash
      run: |
        sudo curl \
          -L https://github.com/input-output-hk/catalyst-ci/releases/download/v${{ inputs.cli_version }}/ci-linux-amd64 \
          -o /usr/bin/ci
        sudo chmod +x /usr/bin/ci
    - name: Check
      shell: bash
      run: ci --help
