name: CI Setup
description: Performs required steps to setup CI.
inputs:
  aws_role_arn:
    description: |
      The ARN of the AWS role to configure credentials for. If this input is
      omitted, AWS credentials will not be configured in the environment.
    required: false
    default: ""
  aws_region:
    description: |
      The default AWS region to use in all requests. If this input is omitted,
      AWS credentials will not be configured in the environment.
    required: false
    default: ""
  cli_version:
    description: The version of the CI CLI to install (defaults to latest)
    required: false
    default: latest
  earthly_runner_secret:
    description: |
      The ID of the AWS secret holding Earthly remote runner credentials. This
      secret must contain the runner address and the necessary TLS certificates
      required to authenticate with it. If omitted, a remote Earthly runner will
      not be configured.
    required: false
    default: ""
  earthly_version:
    description: The version of Earthly to install (defaults to latest)
    required: false
    default: latest
outputs:
  token:
    description: The Github token to use for interacting with repositories
    value: ${{ steps.token.outputs.token }}
runs:
  using: composite
  steps:
    - name: Install Earthly
      uses: earthly/actions-setup@v1
      with:
        version: ${{ inputs.earthly_version }}
    - name: Install CLI
      uses: input-output-hk/catalyst-ci/actions/install@setup-action
      with:
        version: ${{ inputs.cli_version }}
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      if: ${{ inputs.aws_region != '' && inputs.aws_role_arn != '' }}
      with:
        role-to-assume: ${{ inputs.aws_role_arn }}
        aws-region: ${{ inputs.aws_region }}
    - name: Setup Remote Runner
      uses: input-output-hk/catalyst-ci/actions/configure-runner@setup-action
      if: ${{ inputs.earthly_runner_secret != '' }}
      with:
        secret: ${{ inputs.earthly_runner_secret }}
