name: CI Setup
description: Performs required steps to setup CI.
inputs:
  aws_ecr_registry:
    description: The address to the ECR registry that will be configured
    required: false
    default: ""
  aws_role_arn:
    description: |
      The ARN of the AWS role to configure credentials for. If this input is
      omitted, AWS credentials will not be configured in the environment.
    required: false
    default: ""
  aws_region:
    description: |
      The default AWS region to use in all requests. If this input is omitted,
      AWS credentials will not be configured in the environment.
    required: false
    default: ""
  cli_skip_install:
    description: If "true", will skip installing the CI CLI
    required: false
    default: "false"
  cli_version:
    description: The version of the CI CLI to install
    required: false
    default: latest
  configure_registries:
    description: If "true", the action will login to container registries
    required: false
    default: "true"
  dockerhub_token:
    description: The token to use for logging into the DockerHub registry
    required: false
    default: ""
  dockerhub_username:
    description: The username to use for logging into the DockerHub registry
    required: false
    default: ""
  earthly_runner_secret:
    description: |
      The ID of the AWS secret holding Earthly remote runner credentials. This
      secret must contain the runner address and the necessary TLS certificates
      required to authenticate with it. If omitted, a remote Earthly runner will
      not be configured.
    required: false
    default: ""
  earthly_skip_install:
    description: If "true", will skip installing Earthly
    required: false
    default: "false"
  earthly_version:
    description: The version of Earthly to install (defaults to latest)
    required: false
    default: latest
  github_token:
    description: Github token used to login to GHCR (defaults to runner token)
    required: false
    default: ${{ github.token }}
runs:
  using: composite
  steps:
  - name: Install Earthly
    uses: earthly/actions-setup@v1
    if: ${{ inputs.earthly_skip_install == 'false' }}
    with:
      version: ${{ inputs.earthly_version }}
  - name: Install CI CLI From Version
    uses: input-output-hk/catalyst-ci/actions/install@fix/ci-cli-build
    if: ${{ inputs.cli_skip_install == 'false' && inputs.cli_version != 'local' }}
    with:
      version: ${{ inputs.cli_version }}
  - name: Build CI CLI
    uses: input-output-hk/catalyst-ci/actions/run@fix/ci-cli-build
    if: ${{ inputs.cli_skip_install == 'false' && inputs.cli_version == 'local' }}
    with:
      artifact: "true"
      artifact_path: "/usr/local/bin"
      earthfile: ../../cli
      targets: release
  - name: Configure AWS Credentials
    uses: aws-actions/configure-aws-credentials@v4
    if: ${{ inputs.aws_region != '' && inputs.aws_role_arn != '' }}
    with:
      role-to-assume: ${{ inputs.aws_role_arn }}
      aws-region: ${{ inputs.aws_region }}
  - name: Login to Docker Hub
    uses: docker/login-action@v3
    if: ${{ inputs.dockerhub_username != '' && inputs.dockerhub_token != '' && inputs.configure_registries == 'true' }}
    with:
      username: ${{ inputs.dockerhub_username }}
      password: ${{ inputs.dockerhub_token }}
  - name: Login to ECR
    uses: docker/login-action@v3
    if: ${{ inputs.aws_role_arn != '' && inputs.aws_ecr_registry != '' && inputs.configure_registries == 'true' }}
    with:
      registry: ${{ inputs.aws_ecr_registry }}
  - name: Login to GitHub Container Registry
    uses: docker/login-action@v3
    if: ${{ inputs.configure_registries == 'true' }}
    with:
      registry: ghcr.io
      username: ${{ github.actor }}
      password: ${{ inputs.github_token }}
  - name: Setup Remote Runner
    uses: input-output-hk/catalyst-ci/actions/configure-runner@fix/ci-cli-build
    if: ${{ inputs.earthly_runner_secret != '' && inputs.earthly_skip_install != 'true' }}
    with:
      secret: ${{ inputs.earthly_runner_secret }}
