name: CI Setup
description: Performs required steps to setup CI.
inputs:
  aws_role_arn:
    description: The ARN of the CI role (used for fetching secrets)
    required: true
  aws_region:
    description: The AWS region to use
    required: true
  cli_version:
    description: The version of the CI CLI to install
    required: false
    default: 1.1.0
  earthly_version:
    description: The version of Earthly to install
    required: false
    default: latest
outputs:
  token:
    description: The Github token to use for interacting with repositories
    value: ${{ steps.token.outputs.token }}
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Earthly
      uses: earthly/actions-setup@v1
      with:
        version: ${{ inputs.earthly_version }}
    - name: Install CLI
      shell: bash
      run: |
        sudo curl \
          -L https://github.com/input-output-hk/catalyst-ci/releases/download/v${{ inputs.cli_version }}/ci-linux-amd64 \
          -o /usr/bin/ci
        sudo chmod +x /usr/bin/ci
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ inputs.aws_role_arn }}
        aws-region: ${{ inputs.aws_region }}
    - name: Fetch Github token
      shell: bash
      id: token
      run: |
        TOKEN=$(aws secretsmanager get-secret-value --secret-id 'global/ci/deploy' | jq -r .SecretString | jq -r .token)
        echo "token=$TOKEN" >>$GITHUB_OUTPUT
    - name: Setup Remote Runner
      uses: ./actions/configure-runner@master
