VERSION 0.8

IMPORT ../earthly/docs AS docs-ci
IMPORT ../utilities/cql-to-d2 AS cql-to-d2-ci
IMPORT .. AS cat-ci
IMPORT ../examples/postgresql AS postgresql-ci

# Copy all the source we need to build the docs
src:
    # Common src setup
    DO docs-ci+SRC

    # Now copy into that any artifacts we pull from the builds.
    COPY --dir cat-ci+repo-docs/repo includes

    # Copy D2 contents to display in the docs.
    COPY cql-to-d2-ci+src/tests/input/test_1.cql src/appendix/examples/diagrams/sample_d2.cql
    COPY cql-to-d2-ci+src/tests/expected_output/test_1.d2 src/appendix/examples/diagrams/sample_d2.d2

    # Copy docs we build in the postgres example.
    COPY --dir postgresql-ci+build/docs src/appendix/examples/built_docs/postgresql

# Build the docs here.
docs:
    FROM +src
    DO docs-ci+BUILD

# Make a docker image that can serve the docs for development purposes.
# This target is only for local developer use.
local:
    DO docs-ci+PACKAGE

    COPY +docs/ /usr/share/nginx/html

    SAVE IMAGE cat-ci-docs:latest
