INHERIT: std-theme.yml

# Project Information
site_name: Project Catalyst - CI Documentation
site_url: https://input-output-hk.github.io/catalyst-ci

# Repository
repo_name: input-output-hk/catalyst-ci
repo_url: https://github.com/input-output-hk/catalyst-ci

# Page tree
nav:
  - Introduction: index.md
  - Onboarding: onboarding/index.md
  - Style Guide: style.md
  - Guides:
      - guides/index.md
      - Languages:
          - Go: guides/languages/go.md
          - Rust: guides/languages/rust.md
          - Python: guides/languages/python.md
          - Flutter/Dart: guides/languages/flutter.md
          - SQL: guides/languages/sql.md
  - Reference:
      - reference/index.md
      - Workflows: reference/workflows.md
      - Actions: reference/actions.md
      - Targets: reference/targets.md
      - UDCs: reference/udc.md
  - Appendix:
      - Earthly: appendix/earthly.md
      - Documentation Examples:
          - Examples: appendix/examples/index.md
          - Abbreviations: appendix/examples/abbreviations.md
          - Admonitions: appendix/examples/admonitions.md
          - Code Formatting: appendix/examples/code-formatting.md
          - Mermaid Diagrams: appendix/examples/mermaid-diagrams.md
          - Kroki Diagrams: appendix/examples/kroki-diagrams.md
      - Important Information:
          - Important Information: appendix/important/index.md
          - Contributing: appendix/important/contributing.md
          - Code of Conduct: appendix/important/coc.md
          - Security: appendix/important/security.md
          - License: appendix/important/license.md

