site_name: Catalyst CI Documentation
docs_dir: src
theme:
  name: material
  features:
    - navigation.indexes
    - navigation.tracking
nav:
  - Introduction: index.md
  - Onboarding:
      - onboarding/index.md
      - Targets: onboarding/targets.md
      - Workflows: onboarding/workflows.md
      - Actions: onboarding/actions.md
      - UDCs: onboarding/udc.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
