INHERIT: std-theme.yml

# cspell: words fontawesome

# Project Information
site_name: Project Catalyst - CI Documentation
site_url: https://input-output-hk.github.io/catalyst-ci

# Repository
repo_name: input-output-hk/catalyst-ci
repo_url: https://github.com/input-output-hk/catalyst-ci

# Page tree - is created automatically.
# See: https://henrywhitaker3.github.io/mkdocs-material-dark-theme/plugins/awesome-pages/

#plugins:
#  - material/tags:
#      tags_file: appendix/index.md

# Tags used in these docs
extra:
  tags:
    HTML5: html
    JavaScript: js
    CSS: css
    Rust: rust
    Flutter: flutter
    Dart: dart
    Python: python
    Go: go
    PostgreSQL: postgres
    Earthly: earthly
    Github: github
    Docker: docker
    Kubernetes: kubernetes

# Icons associated with the tags
theme:
  icon:
    tag:
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css: fontawesome/brands/css3
      rust: simple/rust
      flutter: simple/flutter
      dart: simple/dart
      python: simple/python
      go: simple/go
      postgres: simple/postgresql
      earthly: material/earth-plus
      github: simple/github
      docker: simple/docker
      kubernetes: simple/kubernetes
