VERSION 0.8
IMPORT ../flutter/installer AS flutter-installer

SETUP:
    FUNCTION
    ARG workdir
    FROM mcr.microsoft.com/playwright:v1.57.0-noble
    WORKDIR $workdir

    RUN apt-get update --fix-missing && apt-get install -y apt-utils unzip

    RUN apt-get update && apt-get install -y \
        libnss3 libatk-bridge2.0-0 libdrm-dev libxkbcommon-dev libgbm-dev libasound-dev libatspi2.0-0 libxshmfence-dev postgresql-client xvfb && \
        apt-get clean && \
        rm -rf /var/lib/apt/lists/*
