VERSION 0.8

# cspell: words markdownlint

MDLINT_LOCALLY:
    # DO NOT RUN THIS FUNCTION INSIDE CONTAINER BUILDS.
    # IT IS NOT FOR CONTAINER BUILDS.
    # See: https://github.com/earthly/earthly/issues/580

    # Linting is done with MarkdownLint CLI2
    # See: https://github.com/DavidAnson/markdownlint-cli2
    # We use a special container which includes all rule extensions to markdownlint
    # Notably, we rely on the `max-one-sentence-per-line` rule which helps keep
    # diffs of markdown files small and legible.  This rule is only currently
    # in the `next` branch of `markdownlint`.
    # Container is built by:
    #   https://github.com/DavidAnson/markdownlint-cli2/blob/next/docker/Dockerfile-rules
    FUNCTION

    # Directory we need to run lint checks against.
    ARG --required src

    # Optional `fix` argument.  Must be either not set, or set to `--fix` anything else is an error.
    ARG fix

    # Unlikely this ever needs to be changed.
    ARG cfg_file=.markdownlint-cli2.jsonc

    # Status line for what we are about to do.
    RUN echo Linting Markdown Recursively from: $src

    # Run the linter with the given arguments, and recursively check all markdown files.
    # The directory to be checked `MUST` have a `.markdownlint-sli2.jsonc` file.
    # cspell: words davidanson
    RUN docker run \
        --rm \
        -v $src:/workdir \
        davidanson/markdownlint-cli2-rules:v0.14.0 \
        "**/*.md" \
        --config $cfg_file \
        $fix

# Markdown check used in standard CI target check.
CHECK: 
    # DO NOT RUN THIS FUNCTION INSIDE CONTAINER BUILDS.
    # IT IS NOT FOR CONTAINER BUILDS.
    # See: https://github.com/earthly/earthly/issues/580

    # Linting is done with MarkdownLint CLI2
    # See: https://github.com/DavidAnson/markdownlint-cli2
    # We use a special container which includes all rule extensions to markdownlint
    # Notably, we rely on the `max-one-sentence-per-line` rule which helps keep
    # diffs of markdown files small and legible.  This rule is only currently
    # in the `next` branch of `markdownlint`.
    # Container is built by:
    #   https://github.com/DavidAnson/markdownlint-cli2/blob/next/docker/Dockerfile-rules
    FUNCTION

    ARG src = .

    # Unlikely this ever needs to be changed.
    ARG cfg_file=.markdownlint-cli2.jsonc

    FROM davidanson/markdownlint-cli2-rules:v0.14.0 

    # Status line for what we are about to do.
    RUN echo Linting Markdown Recursively from: $src

    # Run the linter with the given arguments, and recursively check all markdown files.
    # The directory to be checked `MUST` have a `.markdownlint-sli2.jsonc` file.
    # cspell: words davidanson
    WORKDIR /work
    COPY $src .
    RUN markdownlint-cli2 \
        "**/*.md" \
        --config $cfg_file 

# A Test and example invocation of the above FUNCTION.
test-mdlint:
    # Test Markdown lint checks.
    # Run with `earthly -P +test-mdlint

    # Must be run LOCALLY as described above.
    LOCALLY

    ARG src=$(echo ${PWD}/../../)

    DO +MDLINT_LOCALLY --src=${src}
