VERSION --try --global-cache 0.7

# cspell: words USERARCH toolsets rustfmt nextest

# Set up our target toolchains, and copy our files.
builder:
    FROM ./../../earthly/rust+rust-base

    COPY --dir .cargo .config crates .
    COPY Cargo.lock Cargo.toml .
    COPY clippy.toml deny.toml rustfmt.toml .

    DO ./../../earthly/rust+SETUP

## -----------------------------------------------------------------------------
##
## Standard CI targets.
##
## These targets are discovered and executed automatically by CI.

# Run check using the most efficient host tooling
# CI Automated Entry point.
check:
    FROM +builder

    DO ./../../earthly/rust+CHECK

# Test which runs check with all supported host tooling.  Needs qemu or rosetta to run.
# Only used to validate tooling is working across host toolsets.
all-hosts-check:
    BUILD --platform=linux/amd64 --platform=linux/arm64 +check

# Run build using the most efficient host tooling
# CI Automated Entry point.
build:
    FROM +builder

    TRY
        RUN /scripts/std_build.py   --build_flags="" \
                                    --with_test \
                                    --cov_report="coverage-report.info" \
                                    --libs="bar" \
                                    --bins="foo/foo"
    FINALLY
        SAVE ARTIFACT target/nextest/ci/junit.xml example.junit-report.xml AS LOCAL
        SAVE ARTIFACT coverage-report.info example.coverage-report.info AS LOCAL
    END

    SAVE ARTIFACT target/doc doc
    SAVE ARTIFACT target/release/foo foo

    DO ./../../earthly/rust+SMOKE_TEST --bin="foo"

# Test which runs check with all supported host tooling.  Needs qemu or rosetta to run.
# Only used to validate tooling is working across host toolsets.
all-hosts-build:
    BUILD --platform=linux/amd64 --platform=linux/arm64 +build
