# Earthfile containing common scripts for easy reference
VERSION 0.8


# Internal: bash-scripts : Common bash scripts.
bash-scripts:
    FROM scratch

    COPY --dir bash /

    SAVE ARTIFACT /bash /include

# Internal: bash-scripts : Common bash scripts.
python-scripts:
    FROM scratch

    COPY --dir python /

    SAVE ARTIFACT /python /python

# FUNCTION to add our common bash scripts to a container image.
ADD_BASH_SCRIPTS:
    FUNCTION

    COPY --dir +bash-scripts/include /scripts/include

# FUNCTION to add our common bash scripts to a container image.
ADD_PYTHON_SCRIPTS:
    FUNCTION

    COPY --dir +python-scripts/python /scripts/python
