# Common PostgreSQL Earthly builders
VERSION 0.8

IMPORT ../rust/tools AS rust-tools
IMPORT ../../utilities/dbviz AS dbviz
IMPORT ../../utilities/scripts AS scripts

# cspell: words psycopg dbviz

postgres-base:
    FROM postgres:16.4-bookworm

    WORKDIR /root

    # Install necessary packages 
    # Expand this list as needed, rather than adding more tools in later containers.
    RUN apt-get update && apt-get install -y \
        bash \
        build-essential \
        clang \
        cmake \
        colordiff \
        findutils \
        fontconfig \
        fonts-liberation2        \
        graphviz \
        libssl-dev \
        mold \
        openssl \
        pkgconf \
        python3-pip \
        python3-rich \
        python3-psycopg \
        ripgrep \
        wget \
        pipx \
        && rm -rf /var/lib/apt/lists/*

    # Install SQLFluff - Check
    ENV PATH="/root/.local/bin:${PATH}"
    RUN pipx install sqlfluff==3.1.1 && sqlfluff version

    # Get refinery
    COPY rust-tools+tool-refinery/refinery /bin

    # Get dbviz
    COPY dbviz+build/dbviz /bin
    RUN dbviz --help

    # Copy our set SQL files
    COPY --dir sql /sql

    # Universal build scripts we will always need and are not target dependent.
    COPY --dir scripts /scripts
    # Copy our common scripts so we can use them inside the container.
    DO scripts+ADD_BASH_SCRIPTS
    DO scripts+ADD_PYTHON_SCRIPTS

    SAVE ARTIFACT /scripts /scripts

# Common build setup steps.
# Arguments:
#   sqlfluff_cfg - REQUIRED - Location of repos .sqlfluff configuration file.
#   migrations - OPTIONAL - Location of Migrations directory - DEFAULT: ./migrations
#   seed - OPTIONAL - Location of Seed data directory - DEFAULT: ./seed
#   refinery_toml - OPTIONAL - Location of refinery,toml which configures migrations. DEFAULT: ./refinery.toml
BUILDER:
    FUNCTION

    ARG migrations=./migrations
    ARG seed=./seed
    ARG refinery_toml=./refinery.toml
    
    FROM +postgres-base

    WORKDIR /build

    COPY --dir $sqlfluff_cfg .
    COPY --dir $migrations .
    COPY --dir $seed .
    COPY --dir $refinery_toml .

# DOCS - FUNCTION to build the docs, needs to be run INSIDE the BUILDER like so:
# 
# 1. Create a ./docs/diagrams.json which has the options needed to run to generate the docs to /docs
# 2. Define the following targets in your earthfile
#
# builder:
#    DO github.com/input-output-hk/catalyst-ci/earthly/postgresql:<ver>+BUILDER --sqlfluff_cfg=./../../+repo-config/repo/.sqlfluff
#
# build:
#    FROM +builder
#
#    DO github.com/input-output-hk/catalyst-ci/earthly/postgresql:<ver>+BUILD --image_name=<name>
#    DO github.com/input-output-hk/catalyst-ci/earthly/postgresql:<ver>+DOCS
DOCS:
    FUNCTION

    ARG diagrams=./diagrams.json
    ARG migrations=./migrations
    ARG refinery_toml=./refinery.toml

    USER postgres:postgres
    WORKDIR /docs

    COPY $diagrams ./diagrams.json
    COPY --dir $migrations .
    COPY --dir $refinery_toml .

    RUN /scripts/std_docs.py ./diagrams.json

    SAVE ARTIFACT docs /docs



# Linter checks for sql files
CHECK:
    FUNCTION

    RUN /scripts/std_checks.py

# Format sql files
# Just explains how to auto-format sql files.
# Can not do it LOCALLY as the command will change ownership of the fixed files
# if run within docker.
FORMAT:
    FUNCTION

    # Can not run format LOCALLY as it changes permissions of files to root:root
    RUN --no-cache printf "%s\n%s\n%s\n" \
        "SQL can only be formatted locally from the command line." \
        "Run locally installed 'sqlfluff' from the repo root:" \
        "    $ sqlfluff fix ."

# Internal: Integration Test container image
integration-test:
    FROM earthly/dind:alpine-3.18-docker-23.0.6-r7

    RUN apk add --no-cache \
            bash \
            postgresql15-client # We use PostgreSQL 16, but v15 clients will work OK with it.

    COPY +postgres-base/scripts /scripts

    WORKDIR /test


INTEGRATION_TEST_SETUP:
    FUNCTION

    FROM +integration-test


# Build PostgreSQL image.
# REQUIREMENTS: 
#  * prepare migrations files into the `./migrations` dir
#  * prepare seed data files into the `./data` dir (optional)
#  * prepare `refinery.toml` file
# Arguments:
#  * image_name: The name of the image (required).
BUILD:
    FUNCTION
    ARG --required image_name

    USER postgres:postgres

    RUN /scripts/std_build.sh

    ENTRYPOINT ["/scripts/entry.sh"]

    # Push the container...
    SAVE IMAGE ${image_name}:latest

