name: Branch Pages Deleted
on:
  workflow_call:
    inputs:
      earthfile:
        description: |
          The path to the folder containing the Earthfile that will be built.
          This path should be relative to the repository root.
        required: true
        type: string
      target:
        description: |
          The target that will be used to build docs. The target should always
          produce one artifact which is the static site that will be deployed to
          GitHub Pages.
        required: false
        type: string
        default: docs
      aws_role_arn:
        description: |
          The ARN of the AWS role that will be assumed by the workflow. Only
          required when configuring a remote Earthly runner.
        required: false
        type: string
      aws_region:
        description: |
          The AWS region that will be used by the workflow. Only required when
          configuring a remote Earthly runner.
        required: false
        type: string
      ci_cli_version:
        description: |
          The version of the CI CLI to use.
        required: false
        type: string
        default: latest
      earthly_version:
        description: The version of Earthly to use.
        required: false
        type: string
        default: latest
    secrets:
      earthly_runner_address:
        description: |
          The address of the Earthly runner that will be used to build the
          Earthfile.
        required: false
      earthly_runner_secret:
        description: |
          The ID of the AWS secret holding Earthly remote runner credentials.
          This secret must contain the runner address and the necessary TLS
          certificates required to authenticate with it. If omitted, a remote
          Earthly runner will not be configured.
        required: false

jobs:
  delete:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: |
          GIT_BRANCH=$(echo ${{ github.event.ref }} | sed -e "s#refs/heads/##g")
          DEST_DIR_DOCS="branch/${GIT_BRANCH//[^a-zA-Z0-9_]/_}"
          DEST_DIR_TESTS="allure-action/${GIT_BRANCH//[^a-zA-Z0-9_-]/_}"
          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV
          echo "DEST_DIR_DOCS=$DEST_DIR_DOCS" >> $GITHUB_ENV
          echo "DEST_DIR_TESTS=$DEST_DIR_TESTS" >> $GITHUB_ENV

      - name: Clean up
        run: |
          echo "Clean up for branch ${{ env.GIT_BRANCH }} at ${{ env.DEST_DIR_DOCS }} and ${{ env.DEST_DIR_TESTS }}"

      - name: Get current published documentation
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: Remove branches draft docs and test reports
        run: |
          rm -rf ${{ env.DEST_DIR_DOCS }}
          rm -rf ${{ env.DEST_DIR_TESTS}}

      - name: Save updated docs and test reports
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Removed draft docs and test reports for ${{ env.GIT_BRANCH }}
