name: Release CLI Binary

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/cli-release.yml"
      - "cli/**"

permissions:
    contents: write

jobs:
  release:
    runs-on: ubuntu
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - name: Install Earthly
        uses: earthly/actions-setup@v1
        with:
          version: 0.7.6
      - name: Build CLI
        run: earthly ./cli+build && mv ./cli/bin/ci ci-linux-amd64
      - name: Release CLI
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./cli/bin/ci
