name: Build CLI image

on:
  push:
    # branches:
    #     - master
    # paths:
    #     - ".github/workflows/cli.yml"
    #     - "cli/**"

permissions:
  id-token: write
  contents: read
  packages: write

env:
  AWS_REGION: eu-central-1
  AWS_ROLE_ARN: arn:aws:iam::332405224602:role/ci
  EARTHLY_TARGET: docker
  EARTHLY_VERSION: 0.7.6
  GHCR_REGISTRY: ghcr.io/${{ github.repository }}
  TAGS: latest

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      json: ${{ steps.discover.outputs.json}}
    steps:
      - uses: actions/checkout@v3
      - name: Setup CI
        uses: input-output-hk/catalyst-ci/actions/setup@master
        with:
          aws_role_arn: ${{ env.AWS_ROLE_ARN }}
          aws_region: ${{ env.AWS_REGION }}
          earthly_version: ${{ env.EARTHLY_VERSION }}
      - name: Discover Earthfiles
        uses: input-output-hk/catalyst-ci/actions/discover@master
        id: discover
        with:
          parse_images: "true"
          targets: ${{ env.EARTHLY_TARGET }}
  build:
    runs-on: ubuntu-latest
    needs: [discover]
    strategy:
      matrix:
        earthfile: ${{ fromJson(needs.discover.outputs.json) }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup CI
        uses: input-output-hk/catalyst-ci/actions/setup@master
        with:
          aws_role_arn: ${{ env.AWS_ROLE_ARN }}
          aws_region: ${{ env.AWS_REGION }}
          earthly_version: ${{ env.EARTHLY_VERSION }}
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and publish
        uses: input-output-hk/catalyst-ci/actions/build@build
        with:
          earthfile: ${{ matrix.earthfile.path }}
          #earthly_satellite: ${{ secrets.EARTHLY_SATELLITE_ADDRESS }}
          #images: ${{ matrix.earthfile.images }}
          publish: "false"
          #registry: ${{ env.GHCR_REGISTRY }}
          #tags: ${{ env.TAGS }}
          target: ${{ env.EARTHLY_TARGET }}
