# WARNING: If you modify this workflow, please update the documentation

on:
  workflow_call:
    inputs:
      aws_role_arn:
        description: |
          The ARN of the AWS role that will be assumed by the workflow. Only
          required when configuring a remote Earthly runner or AWS ECR.
        required: false
        type: string
      aws_region:
        description: |
          The AWS region that will be used by the workflow. Only required when
          configuring a remote Earthly runner or AWS ECR.
        required: false
        type: string
      deployment_repo:
        description: The URL of the repository containing deployment code
        required: false
        type: string
        default: input-output-hk/catalyst-world
      deployment_root_path:
        description: The root path to deployment files within the deployment repository
        required: false
        type: string
        default: src/kubev2
      earthly_version:
        description: The version of Earthly to use.
        required: false
        type: string
        default: latest
      environment:
        description: The target environment to deploy to
        required: false
        type: string
        default: dev
      updater_version:
        description: The version of the updater CLI to install
        required: false
        default: latest
        type: string
    secrets:
      dockerhub_username:
        description: The token to use for logging into the DockerHub registry.
        required: false
      dockerhub_token:
        description: The token to use for logging into the DockerHub registry.
        required: false
      earthly_runner_address:
        description: |
          The address of the Earthly runner that will be used to build the
          Earthly files.
        required: false
      earthly_runner_secret:
        description: |
          The ID of the AWS secret holding Earthly remote runner credentials.
          This secret must contain the runner address and the necessary TLS
          certificates required to authenticate with it. If omitted, a remote
          Earthly runner will not be configured.
        required: false

env:
  CUE_VERSION: 0.7.0  # Pin to a known working version of CUE

jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      json: ${{ steps.discover.outputs.json }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup CI
        uses: input-output-hk/catalyst-ci/actions/setup@master
        with:
          aws_role_arn: ${{ inputs.aws_role_arn }}
          aws_region: ${{ inputs.aws_region }}
          cli_skip_install: "true"
          configure_registries: "false"
          dockerhub_token: ${{ secrets.dockerhub_token }}
          dockerhub_username: ${{ secrets.dockerhub_username }}
          earthly_version: ${{ inputs.earthly_version }}
          earthly_runner_secret: ${{ secrets.earthly_runner_secret }}
          runner_address: ${{ secrets.earthly_runner_address }}
          updater_skip_install: "false"
          updater_version: ${{ inputs.updater_version }}
      - name: Install CUE
        uses: cue-lang/setup-cue@v1.0.0
        with:
          version: ${{ env.CUE_VERSION }}
      - name: Fetch deployment secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          secret-ids: |
            global/ci/deploy
          parse-json-secrets: true
      - name: Discover deployment files
        id: discover
        run: |
          JSON=$(updater scan -t "GITHUB_SHA=${{ github.sha }}" .)
          echo "${JSON}"
          echo "json=${JSON}" >> $GITHUB_OUTPUT
      - name: Checkout deployment repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.deployment_repo }}
          token: ${{ env.GLOBAL_CI_DEPLOY_TOKEN }}
      - name: Create deployment branch
        run: |
          git checkout -b "auto-deploy-${{ github.sha }}"
      - name: Update deployments
        run: |
          echo '${{ steps.discover.outputs.json }}' > /tmp/updates.json
          updater update deployments \
            -e "${{ inputs.environment }}" \
            -i /tmp/updates.json \
            "${{inputs.deployment_root_path}}"
          cue fmt --simplify $(git diff --name-only)
      - name: Run diff
        run: git --no-pager diff
      - name: Commit changes
        run: |
          git config --global user.email "catalyst-cibot@projectcatalyst.io"
          git config --global user.name "catalyst-cibot"

          git add .
          git commit -m "chore: auto-deploy from ${{ github.event.repository.name }}"
          git push origin "auto-deploy-${{ github.sha }}"
      - name: Sign commit hash
        id: sign
        run: |
          echo -n "${{ env.GLOBAL_CI_DEPLOY_PRIV_KEY }}" | base64 --decode > /tmp/privkey
          COMMIT=$(git rev-parse HEAD)
          SIG=$(updater signing sign -k /tmp/privkey "$COMMIT")
          rm /tmp/privkey

          echo "GIT COMMIT: $COMMIT"

          echo "signature=${SIG}" >> $GITHUB_OUTPUT
      - name: Create PR
        run: |
          BODY="BEGIN-AUTO-DEPLOY-SIGNATURE:${{ steps.sign.outputs.signature }}:END-AUTO-DEPLOY-SIGNATURE"
          gh pr create --title "chore: auto-deploy from ${{ github.event.repository.name }}" --body "$BODY"
        env:
          GITHUB_TOKEN: ${{ env.GLOBAL_CI_DEPLOY_TOKEN }}