name: Dogfood

on:
  push:

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  release:
    uses: ./.github/workflows/release.yml
    with:
      aws_role_arn: arn:aws:iam::332405224602:role/ci
      aws_region: eu-central-1
      earthly_version: 0.7.15
      force_artifact: ${{ github.event_name != 'pull_request' }}
    secrets:
      earthly_runner_address: ${{ secrets.EARTHLY_SATELLITE_ADDRESS }}