name: Dogfood

on:
  push:
    # branches:  # TOOD: remove when done (disables dogfood while testing)
    #   - foobar

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    with:
      aws_ecr_registry: 332405224602.dkr.ecr.eu-central-1.amazonaws.com
      aws_role_arn: arn:aws:iam::332405224602:role/ci
      aws_region: eu-central-1
      ci_cli_version: 'local'
    secrets:
      dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
      dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
      earthly_runner_address: ${{ secrets.EARTHLY_SATELLITE_ADDRESS }}
      earthly_runner_secret: ${{ secrets.EARTHLY_RUNNER_SECRET }}