name: Dogfood

on:
  push:

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: input-output-hk/catalyst-ci/actions/install@setup-action
        with:
          version: 1.3.0
      - name: Test
        run: |
          ls /usr/local/bin
          /usr/local/bin/ci --help
  # release:
  #   uses: ./.github/workflows/release.yml
  #   with:
  #     aws_role_arn: arn:aws:iam::332405224602:role/ci
  #     aws_region: eu-central-1
  #     earthly_version: 0.7.15
  #   secrets:
  #     earthly_runner_address: ${{ secrets.EARTHLY_SATELLITE_ADDRESS }}