name: Dogfood

on:
  push:

permissions:
  id-token: write
  contents: read
  packages: write

env:
  AWS_REGION: eu-central-1
  AWS_ROLE_ARN: arn:aws:iam::332405224602:role/ci
  EARTHLY_TARGET: build
  EARTHLY_VERSION: 0.7.15

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      json: ${{ steps.discover.outputs.json}}
    steps:
      - uses: actions/checkout@v3
      - uses: input-output-hk/catalyst-ci/actions/setup@dogfood
        with:
          aws_role_arn: ${{ env.AWS_ROLE_ARN }}
          aws_region: ${{ env.AWS_REGION }}
          earthly_version: ${{ env.EARTHLY_VERSION }}
      - uses: input-output-hk/catalyst-ci/actions/discover@dogfood
        id: discover
        with:
          targets: ${{ env.EARTHLY_TARGET }}

  build:
    runs-on: ubuntu-latest
    needs: [discover]
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
        earthfile: ${{ fromJson(needs.discover.outputs.json) }}
    steps:
      - uses: actions/checkout@v3
      - name: Check var
        run: echo ${{ matrix.earthfile }}
      - uses: input-output-hk/catalyst-ci/actions/setup@dogfood
        with:
          aws_role_arn: ${{ env.AWS_ROLE_ARN }}
          aws_region: ${{ env.AWS_REGION }}
          earthly_version: ${{ env.EARTHLY_VERSION }}
      - uses: input-output-hk/catalyst-ci/actions/run@dogfood
        id: build
        with:
          earthfile: ${{ matrix.earthfile }}
          target: ${{ env.EARTHLY_TARGET }}
          artifact_output: out
          flags: --platform ${{ matrix.platform }}
          runner_address: ${{ secrets.EARTHLY_SATELLITE_ADDRESS }}
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.earthfile }}-${{ matrix.platform }}-${{ env.EARTHLY_TARGET }}
          path: out