name: Dogfood

on:
  push:

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    with:
      aws_ecr_registry: 332405224602.dkr.ecr.eu-central-1.amazonaws.com
      aws_role_arn: arn:aws:iam::332405224602:role/ci
      aws_region: eu-central-1
      ci_cli_version: 1.3.1
    secrets:
      earthly_runner_address: ${{ secrets.EARTHLY_SATELLITE_ADDRESS }}
      earthly_runner_secret: ${{ secrets.EARTHLY_RUNNER_SECRET }}