on:
  workflow_call:
    inputs:
      target:
        description: |
          The target used to mark release builds. This target should be unique
          across all Earthly files in the repository. The target should always
          produce at least one artifact which is included in the final GitHub
          release when the workflow is triggered by a tag.
        required: false
        type: string
        default: release
      aws_role_arn:
        description: |
          The ARN of the AWS role that will be assumed by the workflow. Only
          required when configuring a remote Earthly runner.
        required: false
        type: string
      aws_region:
        description: |
          The AWS region that will be used by the workflow. Only required when
          configuring a remote Earthly runner.
        required: false
        type: string
      earthly_version:
        description: The version of Earthly to use.
        required: false
        type: string
        default: latest
    secrets:
      earthly_runner_address:
        description: |
          The address of the Earthly runner that will be used to build the
          Earthly files.
        required: false

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      json: ${{ steps.discover.outputs.json}}
    steps:
      - uses: actions/checkout@v3
      - uses: input-output-hk/catalyst-ci/actions/setup@dogfood
        with:
          aws_role_arn: ${{ inputs.aws_role_arn}}
          aws_region: ${{ inputs.aws_region}}
          earthly_version: ${{ inputs.earthly_version}}
      - uses: input-output-hk/catalyst-ci/actions/discover@dogfood
        id: discover
        with:
          targets: ${{ inputs.target }}

  build:
    runs-on: ubuntu-latest
    needs: [discover]
    if: needs.discover.outputs.json != ''
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
        earthfile: ${{ fromJson(needs.discover.outputs.json) }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup CI
        uses: input-output-hk/catalyst-ci/actions/setup@dogfood
        with:
          aws_role_arn: ${{ inputs.aws_role_arn}}
          aws_region: ${{ inputs.aws_region}}
          earthly_version: ${{ inputs.earthly_version}}
      - name: Build artifact
        uses: input-output-hk/catalyst-ci/actions/run@dogfood
        id: build
        with:
          earthfile: ${{ matrix.earthfile }}
          target: ${{ inputs.target }}
          platform: ${{ matrix.platform }}
          runner_address: ${{ inputs.earthly_runner_address }}
          artifact: "true"
      - name: Generate artifact name
        id: artifact
        run: |
          earthfile=$(basename ${{ matrix.earthfile }})
          platform=$(echo '${{ matrix.platform }}' | sed 's/\//-/g')
          echo "name=$earthfile-$platform" >> $GITHUB_OUTPUT
      - name: Compress artifact
        run: |
          cwd=$(pwd)
          cd ${{ steps.build.outputs.artifact }} && tar -czvf "$cwd/${{ steps.artifact.outputs.name }}.tar.gz" .
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.artifact.outputs.name }}
          path: ${{ steps.artifact.outputs.name }}.tar.gz

  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Collect artifacts
        id: collect
        run: echo "artifacts=$(find artifacts -type f -name '*.tar.gz')" >> $GITHUB_OUTPUT
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.collect.outputs.artifacts }}