# WARNING: If you modify this workflow, please update the documentation

on:
  workflow_call:
    inputs:
      privileged:
        description: |
          Whether the workflow should run earthly in privileged mode (earthly -P flag).
        required: false
        type: boolean
        default: false
      target:
        description: |
          The target to run.
        required: true
        type: string
      aws_role_arn:
        description: |
          The ARN of the AWS role that will be assumed by the workflow. Only
          required when configuring a remote Earthly runner.
        required: false
        type: string
      aws_region:
        description: |
          The AWS region that will be used by the workflow. Only required when
          configuring a remote Earthly runner.
        required: false
        type: string
      ci_cli_version:
        description: |
          The version of the CI CLI to use.
        required: false
        type: string
        default: latest
      earthly_version:
        description: The version of Earthly to use.
        required: false
        type: string
        default: latest
    secrets:
      dockerhub_username:
        description: The token to use for logging into the DockerHub registry.
        required: false
      dockerhub_token:
        description: The token to use for logging into the DockerHub registry.
        required: false
      earthly_runner_address:
        description: |
          The address of the Earthly runner that will be used to build the
          Earthly files.
        required: false
      earthly_runner_secret:
        description: |
          The ID of the AWS secret holding Earthly remote runner credentials.
          This secret must contain the runner address and the necessary TLS
          certificates required to authenticate with it. If omitted, a remote
          Earthly runner will not be configured.
        required: false

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      json: ${{ steps.check.outputs.json }}
      paths: ${{ steps.check.outputs.paths }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup CI
        uses: input-output-hk/catalyst-ci/actions/setup@feat/targets-scanner
        with:
          cli_version: ${{ inputs.ci_cli_version }}
          configure_registries: "false"
          earthly_skip_install: "true"
      - name: Discover Earthly files
        uses: input-output-hk/catalyst-ci/actions/discover@feat/targets-scanner
        id: discover
        with:
          targets: ${{ inputs.target }}
      - name: Check for empty output
        id: check
        run: |
          output=$(echo '${{ steps.discover.outputs.json }}' | jq -rc)
          paths=$(echo '${{ steps.discover.outputs.paths }}' | jq -rc)
          if [ "$output" == "null" ]; then
            echo "json=[]" >> $GITHUB_OUTPUT
            echo "paths=[]" >> $GITHUB_OUTPUT
          else
            echo "json=$output" >> $GITHUB_OUTPUT
            echo "paths=$paths" >> $GITHUB_OUTPUT
          fi

  run:
    runs-on: ubuntu-latest
    needs: [discover]
    if: needs.discover.outputs.paths != '[]'
    strategy:
      fail-fast: false
      matrix:
        earthfile: ${{ fromJson(needs.discover.outputs.paths) }}
    steps:
      - name: Get filtered targets
        run: |
          echo ${{ matrix.earthfile }}
          echo ${{ needs.discover.outputs.json }}
          echo ${{ steps.discover.outputs.json }}
          values=$(echo '${{ steps.discover.outputs.json }}' | jq -r --arg key '${{ matrix.earthfile }}' '.[$key][]')
          echo $values
      - uses: actions/checkout@v3
      - name: Setup CI
        uses: input-output-hk/catalyst-ci/actions/setup@feat/targets-scanner
        with:
          aws_role_arn: ${{ inputs.aws_role_arn }}
          aws_region: ${{ inputs.aws_region }}
          cli_version: ${{ inputs.ci_cli_version }}
          dockerhub_token: ${{ secrets.dockerhub_token }}
          dockerhub_username: ${{ secrets.dockerhub_username }}
          earthly_version: ${{ inputs.earthly_version }}
          earthly_runner_secret: ${{ secrets.earthly_runner_secret }}
      - name: Run
        uses: input-output-hk/catalyst-ci/actions/run@feat/targets-scanner
        id: build
        with:
          privileged: ${{ inputs.privileged }}
          earthfile: ${{ matrix.earthfile }}
          runner_address: ${{ secrets.earthly_runner_address }}
          earthfile_map_targets: ${{ needs.discover.outputs.json }}
