name: Semantic Pull Request

on:
  workflow_call:
    inputs:
      types:
        required: false
        type: string
      scopes:
        required: false
        type: string
      requireScope:
        required: false
        type: boolean
        default: false
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🤖 Ensure Semantic Commit Compliance
        if: github.event_name == 'pull_request'
        uses: amannn/action-semantic-pull-request@v5.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: ${{inputs.types}}
          scopes: ${{inputs.scopes}}
          requireScope: ${{inputs.requireScope}}
          validateSingleCommit: false
          ignoreLabels: |
            bot
            wip
            draft
          wip: false
