name: Spell Check

on: pull_request

jobs:
  publish:
    name: Check if everything in the repo is spelled correctly.
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.7.8
      - uses: actions/checkout@v4

      - name: Check spelling of everything
        run: earthly -P +spell-check
