on:
    push:

jobs:
  deploy:
    uses: input-output-hk/catalyst-ci/.github/workflows/deploy.yml@deploy-cue
    with:
      deployment_repo: input-output-hk/catalyst-world
      #images: ${{ inputs.deployment_images }}
    secrets:
      token: ${{ secrets.CI_BOT_TOKEN }}