name: Build CLI image

on:
  push:

permissions:
  id-token: write
  contents: read
  packages: write

env:
  AWS_REGION: eu-central-1
  AWS_ROLE_ARN: arn:aws:iam::332405224602:role/ci

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: input-output-hk/catalyst-ci/actions/setup@actions
        with:
          aws_role_arn: ${{ env.AWS_ROLE_ARN }}
          aws_region: ${{ env.AWS_REGION }}
          earthly_version: 0.7.6
      - uses: actions/checkout@v3
      - uses: input-output-hk/catalyst-ci/actions/discover@actions
        with:
          targets: docker