name: Validate Own Project Fields

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  contents: write
  pull-requests: write
  id-token: write
  repository-projects: write

jobs:
  validate-own-fields:
    uses: ./.github/workflows/validate-project-fields.yml
    with:
      project_number: "102"
    secrets: inherit
