name: Validate Project Fields

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - unassigned

permissions:
  contents: write
  pull-requests: write
  id-token: write
  repository-projects: write

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  AWS_REGION: eu-central-1
  AWS_ROLE_ARN: arn:aws:iam::332405224602:role/ci
  EARTHLY_TARGET: docker
  ECR_REGISTRY: 332405224602.dkr.ecr.eu-central-1.amazonaws.com

jobs:
  validate-project-fields:
    runs-on: ubuntu-latest
    permissions:
      issues: read
      pull-requests: read      
      repository-projects: read
    steps:
      - name: Fetch Validation Script
        uses: actions/checkout@v4
        with:
          repository: input-output-hk/catalyst-ci
          ref: feat/validate-project-fields-in-prs-and-issues-sj
          sparse-checkout: |
            utilities/project-fields-validator/main.py
          sparse-checkout-cone-mode: false

      - name: Setup CI
        uses: input-output-hk/catalyst-ci/actions/setup@master
        with:
          aws_role_arn: ${{ env.AWS_ROLE_ARN }}
          aws_region: ${{ env.AWS_REGION }}
          earthly_runner_secret: ${{ secrets.EARTHLY_RUNNER_SECRET }}

      - name: Set up Python
        uses: actions/setup-python@v5 
        with:
          python-version: '3.13'

      - name: Run Project Fields Validation
        if: always()
        continue-on-error: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
          GITHUB_REPOSITORY: "${{ github.repository }}"
          GITHUB_EVENT_NUMBER: "${{ github.event.number || '0' }}"
          PROJECT_NUMBER: 102
        run: |
          env
          ls -al utilities/project-fields-validator/main.py
