name: Validate Own Project Fields

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  contents: read
  pull-requests: read
  repository-projects: read

jobs:
  validate-own-fields:
    uses: ./.github/workflows/validate-project-fields.yml
    secrets: inherit
