# use with https://github.com/casey/just
#

# cspell: words prereqs, commitlog

default:
    @just --list --unsorted

# Fix and Check Markdown files
format-code:
    ruff check --select I --fix .
    ruff format .

# Fix and Check Markdown files
lint:
    ruff check .

# Pre Push Checks - intended to be run by a git pre-push hook.
pre-push: format-code lint
