[tool.poetry]
name = "project-fields-validator"
version = "0.1.0"
description = ""
authors = ["Catalyst Team"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
